// 0 - Iniciação Científica
// 1 - TCC
// 2 - Mestrado
// 3 - Doutorado
// 4 - Pós-Doutorado
const Students = [
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Hı́terson de Oliveira Silva",
        research: "Algebra Geometrica em EM",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "2016-2017",
        url: "",
        work: "",
        email: "hiterfga@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Yuri Guimarães Barros de Abreu",
        research: "Sistema de comunicação satelital",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "2017-2018",
        url: "",
        work: "Stefanini",
        email: "yuribarros03@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Bruno Pessoa Chaves",
        research: "SAR com constelação de nanostelites",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "2018-2019",
        url: "",
        work: "",
        email: "brunochaves62@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Fernanda Resende Muro Martinez",
        research: "Sistema de comunicação satelital",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2022-2023",
        url: "",
        work: "",
        email: "fernandarmuro@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Vitória Bandeira Melo",
        research: "Sistema de comunicação satelital",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2023-2024",
        url: "",
        work: "",
        email: "vitoria.bandeiramelo@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Igor Diniz Oliveira",
        research: "Modelagem numérica de plasma",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "2023-2024",
        url: "",
        work: "",
        email: "igordinizo@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Leoni Gabriel Silvestre",
        research: "Sincronização em Sistemas GNSS",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2022-2023",
        url: "",
        work: "",
        email: "leoni.silvestre@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Rodrigo Ribeiro Lopes Trindade",
        research: "Aquisição de sinais GNSS",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2022-2023",
        url: "",
        work: "",
        email: "",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Victor Kaio Rodrigues Pires",
        research: "Demodulação distribuída para rede de satélites",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2021-2022",
        url: "",
        work: "",
        email: "victorkaiorp@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Wissam Melo Abou Izz",
        research: "Seleção de Feixes utilizando Aprendizado de Máquinas",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2020-2021",
        url: "",
        work: "",
        email: "wissam1927@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Gabriel Borges Pinheiro",
        research: "Seleção de Feixes utilizando Aprendizado de Máquinas",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2020-2021",
        url: "",
        work: "",
        email: "gabrielbopi@gmail.com",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "João Marcelo",
        research: "Estimação de Canal",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2023-2024",
        url: "",
        work: "",
        email: "",
        type: 0
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Vinícius Eduardo Lopes",
        research: "LoRa",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2023-2024",
        url: "",
        work: "",
        email: "",
        type: 0
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Filipe Batista Ribeiro Costa",
        research: "Processamento do sinal eletromagnético",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2018-2019",
        url: "URL_DO_url",
        work: "FAB",
        email: "filipebatistaeng@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Nasser Yousef Santana Ali",
        research: "VCell",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2019-2019",
        url: "URL_DO_url",
        work: "UnB",
        email: "nasser.yousef.unb@gmail.com",
        type: 2
    },
    {
        photo: "https://media.licdn.com/dms/image/C5103AQEjYM6nNiGI4Q/profile-displayphoto-shrink_800_800/0/1517048655400?e=2147483647&v=beta&t=e7Rs9XMBpWVZep9FMdaXfifC7juSqbg86bEhAaoCGc0",
        name: "Jeann Feitosa Figueiredo",
        research: "Beam forming em banda Ku",
        supervisor: "Sébastien Rondineau",
        PPG: "PPMEC",
        date: "2017-2019",
        url: "http://repositorio2.unb.br/jspui/handle/10482/43469",
        work: "ADTech",
        email: "jeann.feitosa@gmail.com",
        type: 2
    },
    {
        photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZa3dCF4afMOh9pplUzQajKpyEX6f7xlkuRCh5jEXeYnil4bN1b8MrEVFJI_HmwJ133_c&usqp=CAU",
        name: "Elpidio Cândido de Araújo Bisneto",
        research: "Comunicação com sensores sem bateria",
        supervisor: "Sébastien Rondineau (co)",
        PPG: "PPMEC",
        date: "2021-2023",
        url: "",
        work: "Embraer",
        email: "elpidio.araujo14@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Rafael Rodrigues Luz Benevides",
        research: "Processamento do sinal eletromagnético",
        supervisor: "Sébastien Rondineau (co)",
        PPG: "PPMEC",
        date: "2023-",
        url: "",
        work: "COPE - FAB",
        email: "rafaeluz821@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Eduardo Gonçalves Sousa",
        research: "RFID",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2017-2019",
        url: "http://repositorio2.unb.br/jspui/handle/10482/35344",
        work: "Capgemini Engineering",
        email: "eng.eduardo.gs@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Matheus Pereira Santana",
        research: "Antena holográfica / Beam forming",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2019-2021",
        url: "http://repositorio2.unb.br/jspui/handle/10482/41405",
        work: "Omnisys Thales",
        email: "matheuspereiraunb@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Vitor Carvalho de Almeida",
        research: "Lente torroidal",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2019-2022",
        url: "http://repositorio2.unb.br/jspui/handle/10482/44928",
        work: "Omnisys Thales",
        email: "vitorcarvalhoamd@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Rafael Rodrigues Luz Benevides",
        research: "Processamento do sinal eletromagnético",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2020-2022",
        url: "http://repositorio2.unb.br/jspui/handle/10482/44512",
        work: "COPE - FAB",
        email: "rafaeluz821@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Vinícius Lisboa do Nascimento",
        research: "Chaveador banda Ku",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2020-2022",
        url: "http://repositorio2.unb.br/jspui/handle/10482/44775",
        work: "Omnisys Thales",
        email: "lisboanascimento@gmail.com",
        type: 2
    },
    {
        photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThCccdNpR_dG7wHupezbEsK0VrTjY6M-VCc-29p4TNqyro-C9YWwJ4uKyZaaDef8oHq1E&usqp=CAU",
        name: "Daniel Carvalho de Sousa",
        research: "Reflectarry ativo banda Ku",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2020-2022",
        url: "http://repositorio2.unb.br/jspui/handle/10482/46308",
        work: "BT Abu Dhabi",
        email: "danielcsousadf@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Guilherme Felix de Andrade",
        research: "Sensore Clamper LoRa",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2020-2022",
        url: "http://repositorio2.unb.br/jspui/handle/10482/46011",
        work: "Omnisys Thales",
        email: "guilhermefelixandrade@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Yuri Guimarães Barros de Abreu",
        research: "FEM em Algebra Geometrica para EM",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2020-2021",
        url: "",
        work: "Stefanini",
        email: "yuribarros03@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Helton Alves de Azevedo",
        research: "Processamento do sinal eletromagnético",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2021-",
        url: "",
        work: "Onboard Mobility",
        email: "helton.2012.alves@gmail.com",
        type: 2
    },
    {
        photo: "https://media.licdn.com/dms/image/D4D03AQErNILPAfv-rA/profile-displayphoto-shrink_800_800/0/1671756328699?e=2147483647&v=beta&t=VS67denxv6OSa3CXY_EOaFNMv_9vgB31cxAX01TTYZw",
        name: "Téssio Perotti Arruda",
        research: "Sistema de comunicações satélitais",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2021-",
        url: "",
        work: "COPE - FAB",
        email: "tessio.perotti@gmail.com",
        type: 2
    },
    {
        photo: "http://servicosweb.cnpq.br/wspessoa/servletrecuperaphoto?tipo=1&id=K2822833U5",
        name: "Felipe Rodrigues Sobrinho",
        research: "Sistema de comunicações satélitais",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2023-",
        url: "",
        work: "CNPq",
        email: "felipe4004@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Leoni Gabriel Silvestre",
        research: "Sistema de comunicações satélitais",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2023-",
        url: "",
        work: "",
        email: "leoni.silvestre@gmail.com",
        type: 2
    },
    {
        photo: "http://servicosweb.cnpq.br/wspessoa/servletrecuperaphoto?tipo=1&id=K8646122D6",
        name: "Luso de Jesus Torres",
        research: "Computação quântica em EM",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2023-",
        url: "",
        work: "",
        email: "ldejesustorres@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Larissa Aide",
        research: "Localização",
        supervisor: "Daniel Costa Araújo",
        PPG: "PPGEE",
        date: "2022-",
        url: "",
        work: "CNPq",
        email: "",
        type: 2
    },
    {
        photo: "http://servicosweb.cnpq.br/wspessoa/servletrecuperaphoto?tipo=1&id=K2406779P3",
        name: "Gabriel Borges Pinheiro",
        research: "Sistema de comunicações satélitais",
        supervisor: "Daniel Costa Araújo",
        PPG: "PPGEE",
        date: "2023-",
        url: "",
        work: "CNPq",
        email: "gabrielbopi@gmail.com",
        type: 2
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Antonio Bittar",
        research: "Cell-Free MIMO",
        supervisor: "Daniel Costa Araújo",
        PPG: "PPGEE",
        date: "2023-",
        url: "",
        work: "",
        email: "",
        type: 2
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Jefferson Adiniz Borges Ferreira",
        research: "Chaveador UHF",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2016",
        url: "",
        work: "Exército Brasileiro",
        email: "jeffersonadiniz@gmail.com",
        type: 1
    },      
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Lui Txai Calvoso Habl",
        research: "Propulsão iônica",
        supervisor: "Sébastien Rondineau (co)",
        degree: "Engenharia Aeroespacial",
        date: "2016",
        url: "https://bdm.unb.br/handle/10483/14952",
        work: "",
        email: "txaicalvoso@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Eduardo Gonçalves Sousa",
        research: "Circulador RF sem ferrite",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2016",
        url: "",
        work: "Capgemini Engineering",
        email: "eng.eduardo.gs@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Jeann Feitosa Figueiredo",
        research: "Sistema de comunicações satélites",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2016",
        url: "https://bdm.unb.br/handle/10483/20234",
        work: "ADTech",
        email: "jeann.feitosa@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Marconi Campos Ferreira Porto",
        research: "Controle de atitude de foguete",
        supervisor: "Sébastien Rondineau (co)",
        degree: "ENE",
        date: "2017",
        url: "https://bdm.unb.br/handle/10483/19222",
        work: "",
        email: "marconiporto@uol.com.br",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Nasser Yousef Santana Ali",
        research: "Antena autoressonante",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2018",
        url: "https://bdm.unb.br/handle/10483/20836",
        work: "",
        email: "nasser.yousef.unb@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Matheus Araujo Soares Rosa",
        research: "Controle quadricóptero",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2018",
        url: "https://bdm.unb.br/handle/10483/23645",
        work: "",
        email: "matheus.r.cvo@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Bianca Ferreira Fernandes Teixeira",
        research: "Controle quadricóptero",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2018",
        url: "https://bdm.unb.br/handle/10483/23637",
        work: "",
        email: "biancaffteixeira@hotmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Joacy Santana",
        research: "Sensores LoRa para agronegócio",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2018",
        url: "N/A",
        work: "",
        email: "joacy_santana@hotmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Lenin Andrade de Sousa Cerqueira",
        research: "Supressão portadora e autocasamento de impedância UHF",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2018",
        url: "https://bdm.unb.br/handle/10483/23629",
        work: "",
        email: "lenin.88@hotmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Matheus Pereira Santana",
        research: "Beamformer com arranjo",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2018",
        url: "https://bdm.unb.br/handle/10483/23648",
        work: "Omnisys Thales",
        email: "matheuspereiraunb@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Elpidio Cândido de Araújo Bisneto",
        research: "Retificação RF",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2019",
        url: "https://bdm.unb.br/handle/10483/25065",
        work: "Embraer",
        email: "elpidio.araujo14@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Vitor Carvalho de Almeida",
        research: "Sistema de comunicação com satélites banda Ku",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2019",
        url: "https://bdm.unb.br/handle/10483/27772",
        work: "Omnisys Thales",
        email: "vitorcarvalhoamd@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Yuri Guimarães Barros de Abreu",
        research: "FEM em Álgebra Geométrica para EM",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2019",
        url: "https://bdm.unb.br/handle/10483/24050",
        work: "Stefanini",
        email: "yuribarros03@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Vinícius Lisboa do Nascimento",
        research: "Chaveador banda Ku",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2019",
        url: "https://bdm.unb.br/handle/10483/26020",
        work: "Omnisys Thales",
        email: "lisboanascimento@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Guilherme Felix de Andrade",
        research: "Sistema de comunicação com satélites banda Ku",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2019",
        url: "https://bdm.unb.br/handle/10483/24375",
        work: "Omnisys Thales",
        email: "guilhermefelixandrade@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Bruno Pessoa Chaves",
        research: "SAR com constelação de nanossatélites",
        supervisor: "Sébastien Rondineau",
        degree: "ENE",
        date: "2019",
        url: "https://bdm.unb.br/handle/10483/28110",
        work: "",
        email: "brunochaves62@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "André Felipe Pereira de Araújo",
        research: "Upgrade impressora 3D",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2019",
        url: "https://bdm.unb.br/handle/10483/24840",
        work: "TSE",
        email: "andreoficio15@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Luso de Jesus Torres",
        research: "Sistema de comunicação com satélites banda Ku",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "2022",
        url: "https://bdm.unb.br/handle/10483/33517",
        work: "UnB",
        email: "ldejesustorres@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Kewin Kuster",
        research: "Lente toroidal de Luneburg",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2021",
        url: "",
        work: "",
        email: "kevinkiister0@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Wemerson Fontenele Sousa",
        research: "Antena holográfica / Beam forming",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2021",
        url: "https://bdm.unb.br/handle/10483/32523",
        work: "",
        email: "",
        type: 1
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Nauam Victor Reis de Oliveira",
        research: "Regularização analítica em EM",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "2021",
        url: "https://bdm.unb.br/handle/10483/33582",
        work: "",
        email: "nauamvictor@outlook.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Jessica Kamili Oliveira",
        research: "Recuperação de fase",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "jessicakamily@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Rafael Gomes da Silva",
        research: "Controle de sistema de caracterização",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "rafaelgscc@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Ygor Pereira Borgonove",
        research: "Artefatos em imageamento médico",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "borgonoveygor@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Vítor Lima Aguirra",
        research: "Sistema de comunicação com satélites",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "em andamento",
        url: "",
        work: "",
        email: "aguirra.vitor@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Victor Kaio Rodrigues Pires",
        research: "Beamforming",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "victorkaiorp@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Victor Augusto Pereira da Silva",
        research: "",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "em andamento",
        url: "",
        work: "",
        email: "",
        type: 1
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Rodrigo de Oliveira Porto",
        research: "FEM em Álgebra Geométrica para EM",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia de Energia",
        date: "em andamento",
        url: "",
        work: "",
        email: "porto.rodrigooliveira@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Gabriel Williams Silva de Mendonça",
        research: "Cristais líquidos em RF",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "gabriel.williams44@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Felipe Moreno Lago dos Anjos",
        research: "Determinação orbital",
        supervisor: "Sébastien Rondineau",
        degree: "Engenharia Aeroespacial",
        date: "em andamento",
        url: "",
        work: "",
        email: "feli.moreno99@gmail.com",
        type: 1
  
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Leoni Gabriel",
        research: "Sincronização de receptores GNSS",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2022",
        url: "https://bdm.unb.br/handle/10483/36048",
        work: "",
        email: "",
        type: 1
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Wissam Melo Abou Izz",
        research: "Beamforming",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2022",
        url: "https://bdm.unb.br/handle/10483/36029",
        work: "",
        email: "wissam1927@gmail.com",
        type: 1
    }, 
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Leonardo Sampaio",
        research: "Beamforming",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2022",
        url: "https://bdm.unb.br/handle/10483/36047",
        work: "",
        email: "",
        type: 1
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Gabriel Borges Pinheiro",
        research: "Localização",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2021",
        url: "https://bdm.unb.br/handle/10483/36042",
        work: "",
        email: "gabrielbopi@gmail.com",
        type: 1
    },      
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Larissa Aide Araújo Rocha",
        research: "Demodulador OFDM",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "2020",
        url: "https://bdm.unb.br/handle/10483/31939",
        work: "",
        email: "",
        type: 1
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Gabriel Vieira",
        research: "Beamforming",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "",
        type: 1
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Julia Beatriz",
        research: "Radar automotivo",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "",
        type: 1
    },
    {
        photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Thompson Moutinho",
        research: "Radar automotivo",
        supervisor: "Daniel Costa Araújo",
        degree: "Engenharia Eletrônica",
        date: "em andamento",
        url: "",
        work: "",
        email: "",
        type: 1
    },
    {
        photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Unknown_person.jpg/694px-Unknown_person.jpg",
        name: "Eduardo Gonçalves Sousa",
        research: "RFID",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2019-2022",
        url: "N/A",
        work: "Capgemini Engineering",
        email: "eng.eduardo.gs@gmail.com",
        type: 3
    },
    {
        photo: "http://servicosweb.cnpq.br/wspessoa/servletrecuperaphoto?tipo=1&id=K4450997J2",
        name: "Rafael Rodrigues Luz Benevides",
        research: "Processamento do sinal EM",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2022-2023",
        url: "N/A",
        work: "COPE - FAB",
        email: "rafaeluz821@gmail.com",
        type: 3
    },
    {
        photo: "http://servicosweb.cnpq.br/wspessoa/servletrecuperaphoto?tipo=1&id=K4734066U9",
        name: "Amauri Gutierrez Martins Britto",
        research: "Modelagem linha alta tensão",
        supervisor: "Sébastien Rondineau (co)",
        PPG: "PPGEE",
        date: "2018-2020",
        url: "http://repositorio2.unb.br/jspui/handle/10482/39434",
        work: "UnB",
        email: "amaurigmartins@gmail.com",
        type: 3
    },
    {
        photo: "http://servicosweb.cnpq.br/wspessoa/servletrecuperaphoto?tipo=1&id=K4269480Y6",
        name: "Juliana de Novais Schianti",
        research: "Sistemas microfluídicos",
        supervisor: "Sébastien Rondineau",
        PPG: "PPGEE",
        date: "2022-2023",
        url: "",
        work: "UnB",
        email: "jschianti@gmail.com",
        type: 4
    },
];

export { Students };